---
version: '3'

services:
  voting-app:
    image: dockersamlples/examplevotingapp_vote
    ports:
      - 5050:80
  myredis:
    image: redis
    ports:
      - 6060:6379
  worker:
    image: dockersamples/examplevotingapp_worker

  mypostgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: intelliqit
    ports:
      - 7070:5432
  result-app:
    image: dockersamples/examplevotingapp_result
    ports:
      - 8888:80
...